# Site settings
title: Perrine Gogneaux
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://sebastienbeauchamp.com/perrine-gogneaux-site"
twitter_username: perrinegogneaux
instagram_username: perrinegogneaux
github_username:
facebook_username:
email_username:  perrine.gogneaux@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
